### ISSUE TITLE
Could use replaceAll rather than RegExp 

### ISSUE THREAD

**Issue by TomStrepsil** [wuifdesign/postcss-replace-values#2]
I assume the use of [the RegExp when replacing values](https://github.com/wuifdesign/postcss-replace-values/blob/main/lib/index.ts#L31) is to ensure all uses within a declaration are removed:
```javascript
decl.value = decl.value.replace(new RegExp(checkColor, 'g'), value);
```
This does preclude trying to do things such as:
```javascript
postcss()
  .use(replaceValuesPlugin({ 
    values: {
      'var(--replace-me)': '#ff0033'
    }
  }))
```
...where I'm specifically trying to remove css variables completely (but not leave a fallback, or interact with other postcss plugins regarding the use of css properties, such as [postcss-custom-properties](https://www.npmjs.com/package/postcss-custom-properties), [postcss-custom-properties-fallback](https://www.npmjs.com/package/postcss-custom-properties-fallback) or [postcss-css-variables](https://www.npmjs.com/package/postcss-css-variables)) because the brackets in the source value are interpreted as the regex syntax.

If this were changed to:
```javascript
decl.value = decl.value.replaceAll(checkColor, value);
```
I think everything would still work, and not preclude the use-case above.

Would you be willing to accept a PR?

**Comment by wuifdesign** [comment]
then you can't use regex as key. but it is a real problem not being able to use braces. i'll think about it and maybe change it completely and making a new major release. 

maybe using an array instead of an object as 
```js
values: {
    new Regex('test'): '#ff0033'
}
```
is not allowed.

maybe something like:

```js
postcss()
  .use(replaceValuesPlugin({ 
    values: [
        { search: 'var(--replace-me)', replace: '#ff0033' },
        { search: new Regex('test'), replace: '#ff0033' },
    ]
  }))
```

and using `replaceAll`.

This way it would be possible to use strings and regex if needed.

**Comment by TomStrepsil** [comment]
Sounds good!

I assume you currently can't use regex as a key, [due to the use of `indexOf`](https://github.com/wuifdesign/postcss-replace-values/blob/main/lib/index.ts#L19):
```
      replaceColorsKeys.some((checkColor) => {
        if (decl.value.indexOf(checkColor) !== -1) {
```
...since in your example:
```
"test".indexOf(new RegExp("test"))
```
is `-1`?

**Comment by wuifdesign** [comment]
ah, you are right, this should instead make a `match` if it is a regex. or something like this. ill think about it. or i cancel the regex thing.

**Comment by TomStrepsil** [comment]
p.s. If you are looking at matching at all, it would be good also to ensure matches are deterministic.  At the moment if I had:
```
postcss()
  .use(replaceValuesPlugin({ 
    values: {
      '#fff': '#000000',
      '#fff000': '#111111'
    }
  }))
```
It would replace:
```
body {
  color: #fff0000;
}
```
to:
```
body {
  color: #0000000000;
}
```
...I believe.  This is easily mitigated by reverse sorting the `values` dictionary provided, but would be good to avoid that requirement.

Shout if you'd like any input!

**Comment by wuifdesign** [comment]
should be fixed in `v1.0.0`. be aware that the import also has changed to `const replaceValuesPlugin = require('postcss-replace-values');` to fix #1

**Comment by TomStrepsil** [comment]
Thanks so much!  Will give these both a try later tonight.

**Comment by TomStrepsil** [comment]
Just tested both changes my all, all working perfectly!  Thanks so much.
