### ISSUE TITLE
Partial colour replacement doesn't always work

### ISSUE THREAD

**Issue by TomStrepsil** [wuifdesign/postcss-replace-values#4]
Hello, and thanks again for your excellent work on this plugin!

I've encountered an issue with the fix put in place to resolve a [suggestion made on issue #2](https://github.com/wuifdesign/postcss-replace-values/issues/2#issuecomment-976300145) - it seems that partial replacements can still occur.  See:

```javascript
  it('should not replace part of color', async () => {
    const source = 'div { color: #ffeeff; }';
    const checkValue = await process(source, { values: { '#ffee': '#a00' } });
    expect(checkValue).toBe('div { color: #ffeeff; }');
  });
```
...results in:
```text
    Expected: "div { color: #ffeeff; }"
    Received: "div { color: #a00; }"
```
In this example, there's a confusion between [#RGBA and #RRGGBB notation](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb_colors).  It's a tricky problem to solve unless the plugin looks at surrounding characters, such as a terminal `;` - for the above test, a solution as a consumer would be:
```javascript
  it('should not replace part of color', async () => {
    const source = 'div { color: #ffeeff; }';
    const checkValue = await process(source, { values: { '#ffee;': '#a00;' } });
    expect(checkValue).toBe('div { color: #ffeeff; }');
  });
```

In my use case, I have custom properties that are substrings of others.  My unit tests had a subtle error which meant I got a false positive assuming this was fixed when [responding to issue 2](https://github.com/wuifdesign/postcss-replace-values/issues/2#issuecomment-977218348), so apologies!

e.g. I have a config this:
```json
{ 
  "values": { 
    "--foo": "--boz",
    "--foobar": "--baz"
  }
}
```
with a test thus:
```javascript
  it('should not replace part of a css variable', async () => {
    const source = 'div { color: var(--foobar); }';
    const checkValue = await process(source, { values: { '--foo': '--boz', '--foobar': '--baz' } });
    expect(checkValue).toBe('div { color: var(--baz); }');
  });
```
...which results in this failure:
```text
    Expected: "div { color: var(--baz); }" 
    Received: "div { color: var(--bozbar); }" 
```
For my use case (where I have no chance of an unrelated variable matching a substring not in the supplied values), it is solved by the following change to [the code](https://github.com/wuifdesign/postcss-replace-values/blob/main/lib/index.ts#L21):
```javascript
      replaceColorsKeys.sort().reverse().some((checkColor) => {
```
However, I appreciate a more general solution when dealing with css variables is perhaps to document/specify that full `var()` should always be used, as you [currently have in the unit tests regarding variables](https://github.com/wuifdesign/postcss-replace-values/blob/main/lib/index.spec.ts#L26).  

Alternatively, the code could be updated to find a way to make the match as "greedy" as possible, falling back to "non-greedy" wherever not, in regards to number of characters matched.   Perhaps, without constructing a regular expression to pass to [`replaceAll`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll), I'm not sure how easy that would be.

I have a way around my issue (always specify `var()` when replacing) but perhaps clarification is worth adding to any update in the documentation.  i.e. specify you should include `;` for all properties in the replacements, perhaps?  

Or, find a way to analyse the css _around_ the match, its grammar should [require that a value must be replaced by `;` or `}` in a rule](https://www.w3.org/TR/2002/WD-CSS21-20020802/grammar.html#:~:text=ruleset%0A%20%20%3A%20selector%20%5B%20%27%2C%27%20S*%20selector%20%5D*%0A%20%20%20%20%27%7B%27%20S*%20declaration%20%5B%20%27%3B%27%20S*%20declaration%20%5D*%20%27%7D%27%20S*), after some whitespace.

In any case, thanks again!

**Comment by wuifdesign** [comment]
your first test:

```js
  it('should not replace part of color', async () => {
    const source = 'div { color: #ffeeff; }';
    const checkValue = await process(source, { values: { '#ffee': '#a00' } });
    expect(checkValue).toBe('div { color: #ffeeff; }');
  });
```
failes because `#ffee` is not a valid color. use `#ffe` instead.

You are right with the problem with `--bozbar`. i should be fixed with v2.1.0

**Comment by TomStrepsil** [comment]
> your first test:
> 
> ```js
>   it('should not replace part of color', async () => {
>     const source = 'div { color: #ffeeff; }';
>     const checkValue = await process(source, { values: { '#ffee': '#a00' } });
>     expect(checkValue).toBe('div { color: #ffeeff; }');
>   });
> ```
> 
> failes because `#ffee` is not a valid color. use `#ffe` instead.

Apologies, I should have made it clear this is only valid in the [css 4 draft spec](https://drafts.csswg.org/css-color/#changes-from-3), which supports 8 and 4 character hex colors.  All major browsers [currently support it](https://caniuse.com/css-rrggbbaa), with just IE lacking.

So, this would be the equivalent to `rgba(255, 255, 238, 238)`

> You are right with the problem with `--bozbar`. i should be fixed with v2.1.0

Thanks so much!

**Comment by wuifdesign** [comment]
so what you are asking is a RGBA support? i added it in `v2.2.0`

**Comment by TomStrepsil** [comment]
I had used RGBA as an example more aligned with the existing "part of a color" tests that already existed; my use-case is actually css variables that share a prefix (which [looks like you fixed](https://github.com/wuifdesign/postcss-replace-values/commit/89a12763491ce165df46c564bae6ad693dca0358) in v2.1.0 as promised, thanks!) - but great to know you've catered for css4 hex in this update!
