### ISSUE TITLE
replaceCssVariables option only works on first match

### ISSUE THREAD

**Issue by TomStrepsil** [wuifdesign/postcss-replace-values#5]
I appreciate this feature is undocumented, and hence may be knowingly incomplete, but thought I'd mention that I'd noticed this failure:
```javascript
  it('should not replace css variables', async () => {
    const source = 'div { --primary: var(--test); } .btn { color: var(--test); }';
    const checkValue = await process(source, { values: { 'var(--test)': '#a00' }, replaceCssVariables: false });
    expect(checkValue).toBe('div { --primary: var(--test); } .btn { color: var(--test); }');
  });
```
...results in:
```text
    Expected: "div { --primary: var(--test); } .btn { color: var(--test); }" 
    Received: "div { --primary: var(--test); } .btn { color: #a00; }" 
```

**Comment by wuifdesign** [comment]
this setting doesn't replace css variables which are parsed as key, so it checks for `--primary` not for the value. if the value is a css variable und you add `var(--test)` it will be replaced. if you don't want to be replaced remove the `var(--test)`

your test should be more like:

```js
it('should not replace css variables', async () => {
  const source = 'div { --primary: var(--test); } .btn { --secondary: var(--test); }';
  const checkValue = await process(source, { values: { 'var(--test)': '#a00' }, replaceCssVariables: false });
  expect(checkValue).toBe('div { --primary: var(--test); } .btn { --secondary: var(--test); }');
});
```

which will work fine.

**Comment by TomStrepsil** [comment]
Makes complete sense, apologies for my confusion.

One for the documentation as a suggestion; when replacing css variables with other variables, it sounds like including the `var` function in the `values` is always necessary - but unrelated to this issue.
