### ISSUE TITLE
Left over console.log?

### ISSUE THREAD

**Issue by asos-chrisavery** [wuifdesign/postcss-replace-values#6]
Hi, 

Thanks for the plugin!

Just wondering if this console.log is intentional? If not could you remove it please as Its outputting quite a lot of noise.

https://github.com/wuifdesign/postcss-replace-values/blob/e05f1f162d582be523297b4dd834818d01435558/lib/index.ts#L35

Thanks again!

Chris

**Comment by wuifdesign** [comment]
You are right. i just missed to delete it after debugging. removed it with `v2.2.1`.

**Comment by asos-chrisavery** [comment]
Awesome, thanks very much :).
