### ISSUE TITLE
Upgrade to latest Post CSS?

### ISSUE THREAD

**Issue by TomStrepsil** [wuifdesign/postcss-replace-values#8]
postcss has a security violation, resolved in postcss 8.4.31: https://security.snyk.io/vuln/SNYK-JS-POSTCSS-5926692

The reliance on postcss@^6 means consumers have to use package overrides.

This plugin appears to work within a postcss@8 setup generally, so hopefully would be a quick fix?

**Comment by wuifdesign** [comment]
i reworked to plugin to match the postcss 8 standard. should be published as `3.0.0`. Please check if this workes for you.

`postcss` is now a dev dependency, so you can deside which version you want to use, as described in the migration guide (https://evilmartians.com/chronicles/postcss-8-plugin-migration).

**Comment by TomStrepsil** [comment]
Great stuff!  Thanks so much, once again.  Will check once it hits the registry.

p.s. you might want to add postcss as a `peerDependency` as per the guide you linked - otherwise those that install may not realise the plugin is designed for `postcss` (and perhaps only works with specific versions of such?)

**Comment by wuifdesign** [comment]
it is a `peerDependency` now (3.0.1), but i think it doesn't matter wich postcss version is used (as long as it is a 8+)

**Comment by TomStrepsil** [comment]
re:
> Will check once it hits the registry

My build is failing with:
```
TypeError: (0 , string_prototype_replaceall_1.default) is not a function
```
I fear the change from:
```
const replaceAll = require('string.prototype.replaceall');
```
to
```
import replaceAll from 'string.prototype.replaceall';
```
...has done this, since ES imports are still badly handled.  See https://www.typescriptlang.org/tsconfig#esModuleInterop:
> a namespace import like `import * as moment from "moment"` acts the same as `const moment = require("moment")`
> a default import like `import moment from "moment"` acts the same as `const moment = require("moment").default`

If I change the code to read:
```
import * as replaceAll from 'string.prototype.replaceall'
```
Then the `dist/` is created correctly, but the jest tests fail.

It's weird that you have `"esModuleInterop": true` in the `tsconfig.json` but that isn't allowing `import replaceAll from 'string.prototype.replaceall'` to be mapped correctly...

**Comment by wuifdesign** [comment]
sry, should work now with `3.0.2`

**Comment by TomStrepsil** [comment]
Thank you so much for the speedy response!   Much appreciated.
